# Generated by Django 3.1.6 on 2021-03-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='choice',
            field=models.CharField(choices=[('SH', 'Shops'), ('HS', 'Hostels'), ('RS', 'Restaurents'), ('HO', 'Hospitals'), ('SM', 'Shopping malls'), ('CH', 'Cinema halls'), ('TS', 'Tourism')], max_length=2),
        ),
    ]
